description: "this is a plugin for the sword which gives critical damage to the animals and monsters and anything in the world even the player!"
api-version: 1.19.3
main: com.github.w0819.critical_sword.plugin.CriticalSword
libraries:
  - io.github.monun.kommand:kommand-core:2.14.0
  - io.github.monun.tap:tap-core:4.16.0
author: w0819
name: Critical_Sword
version: 0.0.1
website: https://www.github.com/w0819